name: Test

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: npm install
        run: |
          npm install

      - name: npm test
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run package
          npm run lint
          npm exec tsc
          npm test

      - name: Configure Cluster
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            mkdir -p /opt
            ASSETS_PATH="$GITHUB_WORKSPACE/assets"
            CONFIGS_PATH=/opt/configs
            FORCE_DB_REFRESH=true
            ENGINE_PATH=/opt/etherealengine
            CLUSTER_ID=test
            OPS_PATH=/opt/ethereal-engine-ops
            PASSWORD= # Github actions run in password-less sudo mode.
            ENABLE_RIPPLE_STACK=false

            # TODO: organize this cleanly before merging
            mkdir -p "$CONFIGS_PATH"
            curl https://gist.githubusercontent.com/CITIZENDOT/2c04f2b94a0a36923a82d9c2f6a79815/raw/0a6f47cd2fd25613a0e40f64e6f9befe1c7bde67/test-engine.values.yaml -o "$CONFIGS_PATH/test-engine.values.yaml"

            sudo bash "$ASSETS_PATH/scripts/configure-microk8s-linux.sh" \
            -a "$ASSETS_PATH" \
            -c "$CONFIGS_PATH" \
            -d "$FORCE_DB_REFRESH" \
            -f "$ENGINE_PATH" \
            -i "$CLUSTER_ID" \
            -o "$OPS_PATH" \
            -p "$PASSWORD" \
            -r "$ENABLE_RIPPLE_STACK"
          fi
        shell: bash
        if: matrix.os == 'ubuntu-latest'
