name: Test Congure scripts

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      
      - name: Get all test, doc and src files that have changed
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files_yaml: |
            scripts:
              - assets/scripts/**
              - .github/test-scripts.yml

      - name: Configure MicroK8s Cluster
        if: ${{ (matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest') && steps.changed-files.outputs.scripts_any_modified == 'true' }}
        run: |
          sudo apt install sed
          mkdir -p /opt

          ASSETS_PATH="$GITHUB_WORKSPACE/assets"
          CONFIGS_PATH=/opt/configs
          FORCE_DB_REFRESH=true
          ENGINE_PATH=/opt/etherealengine
          CLUSTER_ID=test
          OPS_PATH=/opt/ethereal-engine-ops
          PASSWORD= # Github actions run in password-less sudo mode.
          ENABLE_RIPPLE_STACK=false

          mkdir -p "$CONFIGS_PATH"
          curl https://raw.githubusercontent.com/EtherealEngine/ethereal-engine-ops/master/configs/local.microk8s.template.values.yaml -o "$CONFIGS_PATH/test-engine.values.yaml"
          sed -i "s,^\([[:space:]]*hostUploadFolder:\).*,\1 '/opt'," "$CONFIGS_PATH/test-engine.values.yaml"

          sudo bash "$ASSETS_PATH/scripts/configure-microk8s-linux.sh" \
          -a "$ASSETS_PATH" \
          -c "$CONFIGS_PATH" \
          -d "$FORCE_DB_REFRESH" \
          -f "$ENGINE_PATH" \
          -i "$CLUSTER_ID" \
          -o "$OPS_PATH" \
          -p "$PASSWORD" \
          -r "$ENABLE_RIPPLE_STACK"
        shell: bash
